apiVersion: batch/v1
kind: Job
metadata:
  name: sample-paralleljob
spec:
  completions: 10
  parallelism: 3
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: tools-container
        image: ezotaka/tools:arm64
        command: ["sleep"]
        args: ["30"]
      restartPolicy: Never
