---
apiVersion: v1
kind: Pod
metadata:
  name: sample-named-port-pod-80
  labels:
    app: sample-app
spec:
  containers:
  - name: nginx-container
    image: ezotaka/echo-nginx:arm64
    ports:
    - name: http # ポートに名前付け
      containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-named-port-pod-81
  labels:
    app: sample-app
spec:
  containers:
  - name: nginx-container
    image: ezotaka/echo-nginx:arm64
    env:
    - name: NGINX_PORT
      value: "81"
    ports:
    - name: http # ポートに名前付け
      containerPort: 81
