apiVersion: v1
kind: Pod
metadata:
  name: sample-rootfile-readonly
spec:
  containers:
  - name: tools-container
    image: ezotaka/tools:arm64
    securityContext:
      readOnlyRootFilesystem: true
