apiVersion: v1
kind: Pod
metadata:
  name: sample-pull-secret
spec:
  containers:
    - name: secret-image-container
      image: ezotaka/private:echo-nginx
  imagePullSecrets:
    - name: sample-registry-auth
