apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-vpa-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: vpa-container
        image: ezotaka/tools:arm64
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
      - name: no-vpa-container
        image: ezotaka/tools:arm64
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
